### ISSUE TITLE
Call to a member function parseEntityFields() on paragraph creatio

### ISSUE THREAD

**Issue by bserem** [miiimooo/behat-tools#2]
I am trying to create a paragraph with behat-tools but without any success.
Maybe I am missing something.

I have this in my scenario:
```
  Scenario: Create a node                                                       
    Given a "par_text" paragraph named "text_paragraph":                           
      | field_par_text | Lorem Ipsum |
```

And I get this when I try to test:
```
  Scenario: Create a node                                               # features/api.feature:5
    Given a "par_text" paragraph named "text_paragraph":                # miiimooo\BehatTools\Context\ParagraphsContext::createParagraph()
      | field_par_text | Lorem Ipsum |
      Fatal error: Call to a member function parseEntityFields() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
    │
    ╳  Unable to access the response content before visiting a page (Behat\Mink\Exception\DriverException)
    │
    └─ @AfterStep # miiimooo\BehatTools\Context\DavScreenshotFailureContext::takeScreenshotAfterFailedStep()
```

This is my `behat.yml`:
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - miiimooo\BehatTools\Context\ParagraphsContext
        - miiimooo\BehatTools\Context\DavScreenshotFailureContext
      failure_path: %paths.base%/screenshots
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      #base_url: http://localhost
    Drupal\DrupalExtension:
      blackbox: ~

# Usage: bin/behat --profile=local
local:
  extensions:
    Behat\MinkExtension:
      base_url: 'http://0.0.0.0:8888'
    Drupal\DrupalExtension:
      drush:
        alias: '@self'
      api_driver: 'drupal'
      drupal:
        drupal_root: '/home/bserem/Development/drupal87/web'
      text:
        log_out: "Manage" # A logged in user can see the Manage link in the admin toolbar
```
